In [2]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

In [3]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__() #inheritance parent class
        self.fc1 = nn.Linear(1,1)
    def forward(self, x):
        x = self.fc1(x)
        return x

In [4]:
net = Net()
print(net)

Net(
  (fc1): Linear(in_features=1, out_features=1, bias=True)
)


In [5]:
print(list(net.parameters()))


[Parameter containing:
tensor([[0.2062]], requires_grad=True), Parameter containing:
tensor([-0.9543], requires_grad=True)]


In [6]:
input = Variable(torch.randn(1,1,1), requires_grad=True)
print(input)


tensor([[[0.4485]]], requires_grad=True)


In [9]:
out = net(input)
print(out)

tu=1*(-0.9543)+0.4485*(0.2062) #operation done 
tu

tensor([[[-0.8619]]], grad_fn=<ThAddBackward>)


-0.8618193000000001

In [10]:
import torch.optim as optim
def criterion(out, label):
    return (label - out)**2
optimizer = optim.SGD(net.parameters(), lr=0.01, momentum=0.5)

In [11]:
#  Ax + b will be that A=3 and b=0

In [12]:
data = [(1,3), (2,6), (3,9), (4,12), (5,15), (6,18)]


In [14]:
for epoch in range(100):
    for i, data2 in enumerate(data):
        X, Y = iter(data2)
        X, Y = Variable(torch.FloatTensor([X]), requires_grad=True), Variable(torch.FloatTensor([Y]), requires_grad=False)
        optimizer.zero_grad()
        outputs = net(X) ##calling forward pass
        loss = criterion(outputs, Y)
        loss.backward()
        optimizer.step()
        if (i % 10 == 0):
            print("Epoch {} - loss: {}".format(epoch, loss.data[0]))

Epoch 0 - loss: 5.150070592208067e-09
Epoch 1 - loss: 4.682135568145895e-09
Epoch 2 - loss: 4.20550350099802e-09
Epoch 3 - loss: 3.783725333050825e-09
Epoch 4 - loss: 3.412026217120001e-09
Epoch 5 - loss: 3.0859723665344063e-09
Epoch 6 - loss: 2.751221472863108e-09
Epoch 7 - loss: 2.459273673593998e-09
Epoch 8 - loss: 2.2737367544323206e-09
Epoch 9 - loss: 2.0090737962163985e-09
Epoch 10 - loss: 1.8010268831858411e-09
Epoch 11 - loss: 1.6427748050773516e-09
Epoch 12 - loss: 1.4734382602910046e-09
Epoch 13 - loss: 1.3306475921126548e-09
Epoch 14 - loss: 1.2116743164369836e-09
Epoch 15 - loss: 1.0668941285985056e-09
Epoch 16 - loss: 9.606537787476555e-10
Epoch 17 - loss: 8.74024408403784e-10
Epoch 18 - loss: 7.914877642178908e-10
Epoch 19 - loss: 7.003677637840156e-10
Epoch 20 - loss: 6.386926543200389e-10
Epoch 21 - loss: 5.913989298278466e-10
Epoch 22 - loss: 5.130118552187923e-10
Epoch 23 - loss: 4.707203515863512e-10
Epoch 24 - loss: 4.204139258945361e-10
Epoch 25 - loss: 3.729496711

In [15]:
## lets see our trained parameters
print(list(net.parameters()))


[Parameter containing:
tensor([[3.]], requires_grad=True), Parameter containing:
tensor([-0.0000], requires_grad=True)]


In [16]:
print(net(Variable(torch.Tensor([[[1]]]))))


tensor([[[3.0000]]], grad_fn=<ThAddBackward>)


In [17]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(1,10)
        self.fc2 = nn.Linear(10,1)
    def forward(self, x):
        x = (self.fc1(x))
        x = self.fc2(x)
        return x

In [18]:
net = Net()


In [ ]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(1,1)
        self.fc2 = nn.Linear(1,1)
    def forward(self, x):
        x = F.relu(self.fc2(F.relu(self.fc1(x))))
        return x
criterion = nn.MSELoss()